### ISSUE TITLE
Can't see Task checkboxes inside Obsidian Columns

### ISSUE THREAD

**Issue by dahliyah** [christianwannerstedt/obsidian-key-value-list#11]
![keyvalue](https://github.com/christianwannerstedt/obsidian-key-value-list/assets/105956987/69f8761f-8ec2-4213-a628-e52d6f65147a)

[Example.md](https://github.com/christianwannerstedt/obsidian-key-value-list/files/13890664/Example.md)

**Comment by christianwannerstedt** [comment]
This is now fixed in the latest release ([1.4.0](https://github.com/christianwannerstedt/obsidian-key-value-list/releases/tag/1.4.0))
