### ISSUE TITLE
Feature Request: Allow for more than one delimiter configuration

### ISSUE THREAD

**Issue by elvarb** [christianwannerstedt/obsidian-key-value-list#15]
The plugin by default uses ":" as a delimiter between they key and the value.

Obsidian allows the use of "::" to define in page properties, as in properties which is not in the front matter. This works perfectly combined with this plugin. What I miss is to be able to also define a key/value list without having it set as a property.

Multiple delimiters in format of "::, :" or just ":: :" would allow the most flexibility

**Comment by christianwannerstedt** [comment]
Hey! This is now fixed in the latest release ([1.7.0](https://github.com/christianwannerstedt/obsidian-key-value-list/releases/tag/1.7.0)). It's now possible to enter a comma separated string as delimiter to support multiple different ones.
