### ISSUE TITLE
BUG? The last character in the Key text is missing in Reading View

### ISSUE THREAD

**Issue by MrBertie** [christianwannerstedt/obsidian-key-value-list#18]
The plugin is working perfectly in Editing View; however when I switch to Reading View the last character in the Key text is missing.

I am running the version 1.5.0 of the plugin, and my Obsidian installation is up to date.

**Comment by christianwannerstedt** [comment]
Hey! This is now fixed in the latest release ([1.6.0](https://github.com/christianwannerstedt/obsidian-key-value-list/releases/tag/1.6.0))
