### ISSUE TITLE
FR: different bullet shown

### ISSUE THREAD

**Issue by Cammagno** [christianwannerstedt/obsidian-key-value-list#4]
Hi, nice idea!
It could be useful to be able to show in the formatted list a different bullet from the one used to trigger the list (adding an option to enter the bullet we want to show instead)

**Comment by christianwannerstedt** [comment]
Hey! That's a great idea, I will make sure to implement this.

**Comment by christianwannerstedt** [comment]
This is now fixed in the latest release ([1.2.0](https://github.com/christianwannerstedt/obsidian-key-value-list/releases/tag/1.2.0))
