### ISSUE TITLE
cssclasses property

### ISSUE THREAD

**Issue by eb2ai** [christianwannerstedt/obsidian-key-value-list#5]
Feature request to use the cssclasses properties to ignore key-value lists on a particular file.

Example
```
---
cssclasses:
 - nokeyvalue
---
```

**Comment by christianwannerstedt** [comment]
Hey!
Yeah, I though about a way to be able to ignore selected files, and this seems like a good solution. I will look into it.

**Comment by christianwannerstedt** [comment]
This is now fixed in the latest release ([1.1.0](https://github.com/christianwannerstedt/obsidian-key-value-list/releases/tag/1.1.0))
