### ISSUE TITLE
The footnote in the list does not work

### ISSUE THREAD

**Issue by OlZin** [christianwannerstedt/obsidian-key-value-list#9]
Hi,
- I didn't see an active Discussion tab, I'm writing here,
- when I use a footnote in the list by `[^]`, my footnote is not active,
- in Editor mode, my `[^1]` has the form of reading, and becomes just `1`,
- in Reading mode, the transition by footnote is not possible,
- it can be fixed,
- Thank you.

**Comment by christianwannerstedt** [comment]
Hey! This is now fixed in the latest release ([1.3.0](https://github.com/christianwannerstedt/obsidian-key-value-list/releases/tag/1.3.0))
